version: '3.8'

services:
  primintel:
    image: ghcr.io/sukya/primintel:latest
    container_name: primintel
    restart: always
    ports:
      - "9900:9900"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config.json:/app/config.json
    networks:
      - agent-net

networks:
  agent-net:
    driver: bridge
